project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - listing.qmd
    - lectures/Intro.qmd
    - lectures/Exponential.qmd
    - lectures/geometric.qmd
    - lectures/Harvest.qmd
    - lectures/Stochasticity.qmd
    - lectures/Extinction.qmd
    - lectures/Competition.qmd
    - lectures/predation.qmd
    - lectures/Age_structure.qmd
    - lectures/population_viability.qmd

website:
  title: "NRM616: Population Ecology"
  site-url: https://drmattg.github.io/PopulationEcologyKMUTT/
  repo-url: https://github.com/DrMattG/PopulationEcologyKMUTT
  repo-actions: [edit, issue]
  page-navigation: true
  search: false
  navbar:
    background: '#BC0031'
    left:
      - text: Lectures
        menu:
          - sidebar:LE
          
    right:
      - icon: github
        href: https://github.com/DrMattG/PopulationEcologyKMUTT
        aria-label: Quarto GitHub

  sidebar:
    - id: LE
      title: "Lectures"
      style: "docked"
      # foreground: '#BC0031'
      background: light
      collapse-level: 2
      contents:
        - listing.qmd
       
format:
  html:
    theme: cosmo
    toc: true
    df-print: kable
    smooth-scroll: true
    link-external-newwindow: true
    linkcolor: '#BC0031'

editor: visual

