---
title: "Population models"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rjags)
```


```{r Exponential growth model}
#exponential growth model
#initial population size
N0<-100
#population growth rate
r<-0.1
#years we are simulating
T<-10
#method 1: use the explicit formula directly 
#first generate a list of time indices
t<-0:T 
#now calculate N at each time
N<-N0*exp(r*t)
#make it pretty
data.frame(t=t,N=N)
plot(t,N,type="l")

```



```{r Add stochastic term}
N0<-100
r.mean<-0.10
r.sd<-0.30
r<-rnorm(T,r.mean,r.sd)
plot(density(r))
abline(v=r.mean,col="blue")
abline(v=r.mean+r.sd,col="blue",lty=2)
abline(v=r.mean-r.sd,col="blue",lty=2)

#now use this in place of the constant r
t<-N<-array(dim=T+1)

#first element is initial value
N[1]<-N0
t[1]<-0
for (i in 1:T)
{
  N[i+1]<-N[i]*exp(r[i])
  t[i+1]=t[i]+1
}
#make it pretty
data.frame(t=t,N=N)
plot(t,N,type="l")
```



```{r Make sure nothing silly happens}
# N to be integer if we want. 
N0<-10
r.mean<-0.0
r.sd<-0.8
r<-rnorm(T,r.mean,r.sd)
plot(density(r))
abline(v=r.mean,col="blue")
abline(v=r.mean+r.sd,col="blue",lty=2)
abline(v=r.mean-r.sd,col="blue",lty=2)

```

```{r Stochastic}

#now use this in place of the constant r
t<-N<-array(dim=T+1)

#first element is initial value
N[1]<-N0
t[1]<-0
for (i in 1:T)
{
  N[i+1]<-round(N[i]*exp(r[i]),0)
  print(N[i+1])
  N[i+1]<-(N[i+1]>1)*N[i+1] #makes N= 0 if falls below 2
  
  t[i+1]=t[i]+1
}
#make it pretty
data.frame(t=t,N=N)
plot(t,N,type="l")

```


```{r density dependent logistic growth}
#continuous growth model
#parameters
T<-50
N0<-100
K<-500
rmax<-0.2
C<-K/N0-1 
#first generate a list of time indices
t<-0:T 
N<-K/(1+C*exp(-rmax*t))
#make it pretty
data.frame(t=t,N=N)
plot(t,N,type="l")

```


```{r Iterative approach using discrete model formulation }
#### 
T<-50
N0<-100
K<-500
rmax<-0.2

t<-N<-array(dim=T+1)

#first element is initial value
N[1]<-N0
t[1]<-0
for (i in 1:T)
{
  N[i+1]<-N[i]+rmax*N[i]*(1-N[i]/K)
  t[i+1]=t[i]+1
}
#make it pretty
data.frame(t=t,N=N)
plot(t,N,type="l")


```

```{r add a stochastic term eg rmax is stochastically influenced by environment}
T<-50
N0<-100
K<-500
rmax.mean<-0.2
rmax.sd<-0.2
rmax<-rnorm(T,rmax.mean,rmax.sd)
t<-N<-array(dim=T+1)
plot(density(rmax))
abline(v=rmax.mean,col="blue")
abline(v=rmax.mean+rmax.sd,col="blue",lty=2)
abline(v=rmax.mean-rmax.sd,col="blue",lty=2)

#first element is initial value
N[1]<-N0
t[1]<-0
for (i in 1:T)
{
  N[i+1]<-N[i]+rmax[i]*N[i]*(1-N[i]/K)
  t[i+1]=t[i]+1
}
#make it pretty
data.frame(t=t,N=N)
plot(t,N,type="l")

```

```{r STOCHASTIC PROCESS ORIENTED MODELS}
#instead of the above approaches we can model growth in terms of F and S directly
#as Poisson and Binomial processes

#AGE STRUCTURE
#Survival rates for four age classes
S=c(0.5,0.75,0.85,0.65)
#births for four age classes
b=c(0,1,2,0)
f=c(b[1]*S[1],b[2]*S[2],b[3]*S[3],b[4]*S[4])
A1=c(S[1],0,0,0)
A2=c(0,S[2],0,0)
A3=c(0,0,S[3],S[4])
A=rbind(f,A1,A2,A3)
A
years=50
#initial abundance vector
N=c(10,100,200,500)
N
#create empty vectors for age vector, time, population, individual ages, and growth rate
age=c()
t=c()
pop=c()
age0=c()
age1=c()
age2=c()
age3=c()
grow=c()
#for loop to simulate population under deterministic conditions
for (y in 1:max(years)){
  t=append(t,y)
  abund=sum(N)
  pop=append(pop,abund)
  for (i in 1:4){age[i]=N[i]/abund}
  age0=append(age0,age[1])
  age1=append(age1,age[2])
  age2=append(age2,age[3])
  age3=append(age3,age[4])
  
  cat("year",y,"\n");
  cat("Population",N,"\n");
  cat("age structure",age,"\n");
  N=A%*%N
  
  grow=append(grow,sum(N)/abund)
  cat("lambda",grow[y],"\n");
}

plot(t,pop,xlab="t",ylab="N",main="Popsize",type="l")
#savePlot(filename="Popsize",type="png")
#win.graph()

```

```{r}
plot(t,age0,xlab="t",ylab="age",main="age_structure",type="l")
lines(t,age1,col="green")
lines(t,age2,col="red")
lines(t,age3,col="blue")
legend("top","age0=black, age1=green, age2=red, age3=blue")
#savePlot(filename="age_structure",type="png")
#win.graph()

```

```{r}
plot(t,grow,xlab="t",ylab="lambda",main="popgrowth_age",type="l")
#savePlot(filename="popgrowth_age",type="png")

```

```{r state spaced model}
nt   <- 200                      # no. time intervals
time <- c(1:nt)                  # sample times
nm   <- 20                       # number of missing values
wm   <- sort(sample(c(2:nt),nm)) # which are missing
sig  <- 5                        # process err variance
tau  <- 20                       # obs error variance
x    <- rep(10,nt)
for(t in 2:nt)x[t] <- x[t-1] + rnorm(1,0,sqrt(sig))

y     <- rnorm(nt,x,sqrt(tau))   # simulate observations
y[wm] <- NA                      # some are missing

plot(time, y, col='grey')
lines(time, x)
points( time[wm], x[wm], pch=16)
```


State-Space Models

```{r simulate data}
nYears <- 25      # Number of years
N1 <- 30           # Initial population size
mu.lambda <- 1.02  # Mean annual population growth rate
sigma.lambda <- 0.15   # Process (temporal) variation of the growth rate
sigma.obs <- 20        # SD of the observation error
```

```{r}
## Empty vectors to store the data
ssm_sim1 <- data.frame(Year = 1:nYears, 
                       y = numeric(nYears),
                       N = numeric(nYears))

## Fill in initial abundance
ssm_sim1$N[1] <- N1

## Randomly generate annual lambda values
lambda <- rnorm(nYears-1, mu.lambda, sigma.lambda)
```

```{r}
## Loop over years 1:nYears - 1 to generate true abundance
for (t in 1:(nYears-1)){
   ssm_sim1$N[t+1] <- ssm_sim1$N[t] * lambda[t]
}

## Loop over all years to generate counts
for (t in 1:nYears){
   ssm_sim1$y[t] <- rnorm(1, ssm_sim1$N[t], sigma.obs)
}

ggplot(ssm_sim1, aes(x = Year)) +
  geom_line(aes(y = N), color = "grey30") +
  geom_point(aes(y = y), color = "red")+
  theme_classic()
```


```{r, eval=FALSE}
sink("ssm.jags")
cat("
model { 
    # Priors and constraints
    N.est[1] ~ dunif(0, 500)  # Initial population size

    for (t in 1:(nYears-1)){
      lambda[t] ~ dnorm(mu.lambda, tau.lambda) 
    }

    mu.lambda ~ dnorm(0, 0.1)          # Mean growth rate
    sigma.lambda ~ dgamma(0.25, 0.25)  # SD of state process
    tau.lambda <- pow(sigma.lambda, -2)
    
    sigma.obs ~ dgamma(0.25, 0.25)     # SD of observation process
    tau.obs <- pow(sigma.obs, -2)
  
    # Likelihood
    # State process
    for (t in 1:(nYears-1)){
      N.est[t+1] <- N.est[t] * lambda[t] 
    }
    # Observation process
    for (t in 1:nYears) {
      y[t] ~ dnorm(N.est[t], tau.obs)
    }
    }
    ", fill = TRUE)
sink()
```


```{r}
## Bundle data
jags.data <- list(y = ssm_sim1$y, nYears = nYears)

# Initial values
inits <- function(){list(sigma.lambda = runif(1, 0, 5), 
                         mu.lambda = runif(1, 0.1, 2), 
                         sigma.obs = runif(1, 0, 10), 
                         N.est = c(runif(1, 20, 40), rep(NA, (nYears-1))))} 
```

```{r}
# Parameters monitored
parameters <- c("lambda", "mu.lambda", "sigma.obs", "sigma.lambda", "N.est")

# MCMC settings
ni <- 25000
nt <- 3
nb <- 10000
nc <- 3

# Call WinBUGS from R (BRT <1 min)
ssm <- jagsUI::jags(data = jags.data, inits = inits, parameters.to.save = parameters, 
                    model.file = "ssm.jags", n.chains = nc, n.thin = nt, 
                    n.iter = ni, n.burnin = nb)

print(ssm)
```
```{r}
ssm_sim1 <- dplyr::mutate(ssm_sim1, 
                          Estimated = ssm$mean$N.est, 
                          LCI = ssm$q2.5$N.est, 
                          UCI = ssm$q97.5$N.est)

ggplot(ssm_sim1, aes(x = Year)) +
  geom_ribbon(aes(ymin = LCI, ymax = UCI), fill = "grey80") +
  geom_line(aes(y = Estimated), color = "grey50") +
  geom_line(aes(y = N), color = "grey20") +
  geom_point(aes(y = y), color = "red")+
  theme_classic()
```

